name: DEPLOY-2022
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            php composer install
            php artisan migrate --force
            php artisan cache:clear
